### ISSUE TITLE
email and password works (i tried) remove them !!!!!

### ISSUE THREAD

**Issue by Vicky-42** [MuhammadHamzaAmir/python_selenium_tutorial#1]

**Comment by MuhammadHamzaAmir** [comment]
I don't know how this works for you. But it didn't work for me as I have tried various methods and puppeteer too.
I have removed my email and password.
Can you explain what you added to the script?

**Comment by Vicky-42** [comment]
Hi;
I didn't try the script, I meant the credentials worked (gmail one).
I usually use the scrapy lib.
Good luck dear & have a good day !
